### ISSUE TITLE
Search feature doesnot work

### ISSUE THREAD

**Issue by inkerton** [notsoocool/codecache#9] opened 2024-10-01 16:13 UTC
**Describe the bug**
The search feature is currently not working as I am trying to search a keyword.
**To Reproduce**
1. Go to 'Snippets'
2. Type on Search
3. Add Logic for Search

**Expected behavior**
On search , all the snippets with the searched keyword should be rendered.

**Screenshots**
![image](https://github.com/user-attachments/assets/4856d282-ddf8-4823-b52c-c1ede372d864)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by inkerton** [comment] 2024-10-01 16:14
I would like to work on this issue kindly assign it to me under Gssoc extended and Hacktoberfest.

**Comment by notsoocool** [comment] 2024-10-01 17:51
@inkerton 
Thank you for your enthusiasm! Before moving on to another issue, could you please focus on resolving the current one first? This will help keep the project organized and ensure that progress is made steadily. Once the issue is resolved, feel free to tackle the next one.

**Comment by itznayan** [comment] 2024-10-02 10:34
I would like to work on this issue kindly assign it to me under Gssoc'24 extended and Hacktoberfest.

**Comment by notsoocool** [comment] 2024-10-02 13:49
Sure @itznayan i will assign you this issue, please go through the contributing guidelines before start contributing

**Comment by Ameerjafar** [comment] 2024-10-04 03:41
@notsoocool can you please assign this issue

**Comment by notsoocool** [comment] 2024-10-04 05:40
Sure @Ameerjafar you can go ahead with the issue

**Comment by notsoocool** [comment] 2024-10-06 11:29
@itznayan 
Hello! It's been more than 3 days since this issue was assigned. If you’re still working on it, please provide an update. Otherwise, I will need to remove you from the assignment to free it up for others to take over. Thank you!

**Comment by menerucha** [comment] 2024-10-07 06:45
@notsoocool Assign this task to me under gssoc 2024 ext and hacktoberfest.

**Comment by notsoocool** [comment] 2024-10-07 07:14
Sure @menerucha

**Comment by Rashigera** [comment] 2024-10-08 11:57
Could this be assigned to me

**Comment by notsoocool** [comment] 2024-10-08 12:07
@Rashigera , I appreciate your interest, but @menerucha is already working on the issue. If you'd like, you can choose another issue to work on.

**Comment by menerucha** [comment] 2024-10-10 15:52
Thank you so much @notsoocool. I would be completing my task in a day or two.

**Comment by kanika1206** [comment] 2024-10-12 15:07
hey @notsoocool , I would like to work on this issue kindly assign it to me under Gssoc extended

**Comment by notsoocool** [comment] 2024-10-13 09:32
@kanika1206 go ahead, i will assign you this issue

**Comment by notsoocool** [comment] 2024-10-13 09:33
Hi @menerucha,

It’s been over three days without an update. Please let me know your progress, or I may need to reassign the issue.

Thanks!

**Comment by menerucha** [comment] 2024-10-13 09:47
I am still working on this

**Comment by notsoocool** [comment] 2024-10-13 09:48
okay @menerucha i will wait for 2 more days

**Comment by menerucha** [comment] 2024-10-13 09:49
Yes, I am working on the bugs of the issue

**Comment by notsoocool** [comment] 2024-10-15 18:55
@menerucha Just a reminder, today is the last day for your assigned issue. Please ensure it's completed on time. Let me know if you need any assistance!

**Comment by menerucha** [comment] 2024-10-15 19:08
Yes it will be completed tonight by 7pm

**Comment by Gauravtb2253** [comment] 2024-10-19 17:49
pls assign me

**Comment by notsoocool** [comment] 2024-10-19 17:56
Feel free to start working on this feature. If at any point the code becomes difficult to manage or you need assistance, don't hesitate to ask for help. I'm here to support you! 
@Gauravtb2253

**Closed as completed** 2024-10-21 18:43 UTC
Labels: bug, gssoc-ext, hacktoberfest-accepted, level3
