### ISSUE TITLE
Have a My "Snippets" page to view Snippets added my the user

### ISSUE THREAD

**Issue by ZayedShahcode** [notsoocool/codecache#34] opened 2024-10-05 06:51 UTC
**Is your feature request related to a problem? Please describe.**
When I add a snippet, I can't see it at the home page. Later if I want to search and edit the snippet, it becomes a tedious task.

**Describe the solution you'd like**
Have a separate "My Snippets" page where the user can view and edit all the snippets added by him.

**Describe alternatives you've considered**
Same as mentioned above

**Additional context**
No additional context.

**Comment by notsoocool** [comment] 2024-10-05 07:27
@ZayedShahcode 
Thank you for your enthusiasm! Before moving on to another issue, could you please focus on resolving the current one #33 ? This will help keep the project organised and ensure that progress is made steadily. Once the issue is resolved, feel free to tackle the next one.

**Comment by harish08102004** [comment] 2024-10-05 12:25
Hey @ZayedShahcode I can work on this.

**Comment by notsoocool** [comment] 2024-10-05 13:43
@harish08102004 If you want to work on this issue, i will assign you. Before contributing keep in mind to fetch the `develop` branch and make a **PR** for the same

**Comment by inkerton** [comment] 2024-10-06 12:51
I would like to work on the issue also.

**Comment by notsoocool** [comment] 2024-10-06 13:21
@inkerton That's awesome! 🎉 I really appreciate your enthusiasm—it's great to see you taking on another issue. This will be your second one, and I’m sure you’ll do an amazing job just like before. 🙌 Feel free to reach out if you need any help along the way! 😊

**Comment by notsoocool** [comment] 2024-10-08 11:43
@harish08102004 i will be removing you from the assignees as you haven't updated me science 3 days

**Comment by harish08102004** [comment] 2024-10-08 11:45
Hey @notsoocool I'm working on it.

**Comment by notsoocool** [comment] 2024-10-08 12:04
@harish08102004, I appreciate your interest, but @inkerton has already resolved the issue. If you'd like, you can choose another issue to work on.

**Comment by harish08102004** [comment] 2024-10-08 12:11
Ohh I almost finished.

**Comment by notsoocool** [comment] 2024-10-08 12:13
> Ohh I almost finished. Ok no issues.

I am sorry but you haven't updated me since 3 days thats why i had to assign it to others, feel free to work on other issues as well

**Closed** 2024-10-13 09:42 UTC
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3
